### ISSUE TITLE
Alt-Zoom fails after some time.

### ISSUE THREAD

**Issue by feedface** [LIJI32/MIP#10]
I booted the system and everything works (no complaint from the Helper App). After some time the commands no longer worked: opened the Helper App and sure enough, it said the bundle wasn't installed.
This has happened twice now. A reboot always fixes it.
macOS 12.4 M1-MBA

**Comment by LIJI32** [comment]
This usually means `launchservicesd` crashed and relaunched (so it does not have `lsdinjector.dylib` injected anymore). Do you have any recent crashlog from that process? It could help figuring this issue out.

Fixing this problem without rebooting is possible by reinjecting the dylib: `inject launchservicesd /Library/Apple/System/Library/Frameworks/mip/lsdinjector.dylib`

**Comment by feedface** [comment]
Sorry, this seems to be user error on my part. I am investigating.

**Comment by feedface** [comment]
This was caused by a failed build (bad code sign identity), followed by noob mistake of forgetting bundles were likely removed when doing make uninstall. I apologise for the second issue caused my my ineptitude. Everything working, including further bundles.
