### ISSUE TITLE
Injection not working with pseudo signature (ldid)

### ISSUE THREAD

**Issue by NSExceptional** [LIJI32/MIP#15]
Environment: M2 MacBook Air, macOS 12.6

I built and installed the project, enabled the preview abi boot arg, and rebooted. Then I made and installed the sample bundle. Everything installed fine, I checked. But when I open the Alt-Zoom app, it says it is not installed, which just means the class/plugin wasn't loaded.

The only thing I did differently is I used `ldid -S $@` in place of the `codesign` command in both projects, to pseudo-sign the binaries. I don't know a lot about how code signing works, but I know this is what we use in the jailbreak world to sign binaries, and I am able to use it to sign modified app executables or frameworks to make them run on my mac, so I don't know why that might be an issue here.

Assuming that's not the issue, how do I troubleshoot this? (In the meantime, I'm going to try again with an actual codesigning identity just to be safe)

Edit: that was the issue! Strangely, I only had to re-sign and re-install MIP itself… I can still pseudo sign the tweaks themselves. Not a big deal I guess! I'll close this

**Comment by LIJI32** [comment]
This is actually the issue. Certain binaries on macOS will refuse to load ad-hoc signed dylibs, you need to actually create a code signing certificate with Keychain Access and use it to sign MIP dylibs.

**Comment by NSExceptional** [comment]
Haha I just edited my post right as you replied. Any idea why I can get away with not truly signing the dylibs?

**Comment by LIJI32** [comment]
Been a while since I actually solve that issue, but IIRC it had something to do with the hardened runtime not allowing OS-provided binaries to load ad-hoc signed dylibs. Keep in mind that if you ad-hoc sign your bundles, they will fail to load in OS-provided apps.

**Comment by NSExceptional** [comment]
Ohh gotcha, that explains why it loads with Chrome then
