### ISSUE TITLE
`MIPBundleNames` should function like Substrate's `Bundles`

### ISSUE THREAD

**Issue by NSExceptional** [LIJI32/MIP#16]
Substrate's `Bundles` accepts _any_ bundle identifier, not just application bundle IDs. For example, if you wanted to modify `NSApp.mainMenu` in every app, you would use `com.apple.AppKit`. Your tweak would load into all GUI apps (any process that links AppKit) to make a system wide tweak — without having to use a wildcard bundle and blacklist daemons.

Happy to put up a PR for this if you'd accept it!

**Comment by LIJI32** [comment]
Sounds good to me, go ahead :)
