### ISSUE TITLE
MIP macOS Monterey 12.6.2 M1

### ISSUE THREAD

**Issue by RegulusMac** [LIJI32/MIP#27]
Hello again,
today I discovered an issue with MIP on M1 - macOS 12.6.2
MIP does not work anymore.
I have no idea what it caused - macOS update or XProtect update...
I tried to start it from terminal and got this:

Inject MIP to launchservicesd without a restart? [y/N] y
/bin/sh: line 1:  1378 Killed: 9     sudo inject launchservicesd /Library/Apple/System/Library/Frameworks/mip/lsdinjector.dylib
make: *** [install] Error 137

Watching console I got this:

Acquiring assertion targeting [app<application.com.apple.Console.1152921500311973676.1152921500311973681(501)>:954] from originator [daemon<com.apple.coreservices.launchservicesd>:146] with description <RBSAssertionDescriptor| "notification:954" ID:195-146-763 target:954 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>

Any idea?

PS: MIP still works on my INTEL Mac with Monterey 12.6.2

**Comment by LIJI32** [comment]
`inject` getting killed is most likely a code signing issue. Make sure that:
1. The (self-signed) certificate you're using is still valid
2. There are no console messages from AMFI, `amfid` or the kernel after launching `inject`

Additionally, try cleaning before building.

Let me know if any of these help.

**Comment by RegulusMac** [comment]
Sorry, all mip files are valid signed.
Just checked Ventura macOS 13.2 again with a MIP clean install
and new MIP build with valid code sign cert.
And guess what, now I get the same error messages
like I got with Monterey.
Weird

**Comment by RegulusMac** [comment]
Sorry, I fixed it.
sudo nvram boot-args=-arm64e_preview_abi
was off somehow.

Close or delete this topic!

**Comment by LIJI32** [comment]
Ah right, I forgot updates sometimes have the tendency to turn this one off.
