### ISSUE TITLE
how to know whether inject success in chrome subProcess

### ISSUE THREAD

**Issue by nicholaslin** [LIJI32/MIP#3]
buddy, please tell me how to know whether inject success or not in chrome subProcess when I click new Tab. I print log in console but show nothing , but I saw your "readme" desc that can support it. I just want to know how can I test it. thx

**Comment by LIJI32** [comment]
The easiest way to know if an injection was successful is to attach to it via LLDB and use `image list`. If it worked, it should show `/usr/lib/mip/loader.dylib` in there.

**Comment by nicholaslin** [comment]
> The easiest way to know if an injection was successful is to attach to it via LLDB and use `image list`. If it worked, it should show `/usr/lib/mip/loader.dylib` in there.

thx , I saw it in the chrome main process but other subprocess cannot find it. is it normal phenomenon?

**Comment by LIJI32** [comment]
It depends. Google might have changed the way the subprocesses work, so they might no longer register themselves with `launchservices`. If that's the case, this can be worked around by injecting a MIP bundle to the main process that sets the `DYLD_INSERT_LIBRARIES` env var. If that's not the case, that's a bug that should be fixed.

**Comment by nicholaslin** [comment]
> The easiest way to know if an injection was successful is to attach to it via LLDB and use `image list`. If it worked, it should show `/usr/lib/mip/loader.dylib` in there.

by the way, do you know how can i inject all process not just only the GUI process? I saw your code hook launchServicesd and just handle command == 500 ,can i handle more command ? and where can i learn the magic number is mean for ? Thank you for your generous advice

**Comment by LIJI32** [comment]
Normally, non GUI processes do not communicate via XPC with any other process, so I can't really think of a timing-deterministic method that injects to all of them automatically. You can still use the `inject` command to manually inject a dylib to a process. That 500 is just one of the XPC commands that `launchservicesd` receives. It's not documented, but it's sent when a process calls `_LSApplicationCheckIn`, which is called, for example, from `NSApplicationMain`.

**Comment by nicholaslin** [comment]
> Normally, non GUI processes do not communicate via XPC with any other process, so I can't really think of a timing-deterministic method that injects to all of them automatically. You can still use the `inject` command to manually inject a dylib to a process. That 500 is just one of the XPC commands that `launchservicesd` receives. It's not documented, but it's sent when a process calls `_LSApplicationCheckIn`, which is called, for example, from `NSApplicationMain`.
 
okay, thx for your reply
