### ISSUE TITLE
MIP - Sonoma 14.5 issue

### ISSUE THREAD

**Issue by RegulusMac** [LIJI32/MIP#32]
Today I updated Sonoma to 14.4.b2 and have sad news for MIP
MIP stopped working. I uninstalled it.
After a fresh install I got this in Terminal window:

Injecting to process 142
/bin/sh: line 1: 1665 Killed: 9 sudo inject launchservicesd /Library/Apple/System/Library/Frameworks/mip/lsdinjector.dylib
make: *** [install] Error 137

Any idea ?

**Comment by RegulusMac** [comment]
Updated to 14.4.b4 ...
Same  result.

[inject.helper-2024-02-20-204517.ips.zip](https://github.com/LIJI32/MIP/files/14357868/inject.helper-2024-02-20-204517.ips.zip)

**Comment by RegulusMac** [comment]
Good news, after updated to 14.4 - MIP works again.

I think you can close this issue now.

**Comment by RegulusMac** [comment]
Hi Lior,
sad news again.
MIP doesn't work with latest final Sonoma update 14.5.
Any help would really appreciated.
I have attached the log file.
Thx

[inject-2024-05-14-133543.ips.zip](https://github.com/LIJI32/MIP/files/15307865/inject-2024-05-14-133543.ips.zip)

**Comment by RegulusMac** [comment]
Hi again,
I tried **inject** from command line utility with a third party application and that worked.
So it looks it's kind of launchservicesd problem...

It would be nice if you just gave me/us a sign.
Thx

**Comment by RegulusMac** [comment]
Hello, 
will there be any progress with this issue or will the MIP project be discontinued?

**Comment by LIJI32** [comment]
The last commit should fix newer XNU versions where `thread_set_state` requires an entitlement. This requires setting a bootarg to disable AMFI, so make sure to run `make install` and reboot if required.

**Comment by RegulusMac** [comment]
Ok, because I trust your great work, I updated my Sonoma 14.4.1 directly to 14.5
and all works fine with latest MIP version.

Thx again!
