### ISSUE TITLE
inject tool crash on macOS 14.4

### ISSUE THREAD

**Issue by leochou0729** [LIJI32/MIP#33]
Hi,
When I try to inject some app with the inject tool on macOS 14.4, both the inject tool and the target app would crash. 
I'm using a Intel-based macbook pro, but I think Macs with Apple silicon probably have the same issue.
Attached are the ips files.
[ips.zip](https://github.com/LIJI32/MIP/files/14741732/ips.zip)

**Comment by RegulusMac** [comment]
I'm on macOS 14.4.1 and all is working great.
Only Rosetta 2 is not working for me.

**Comment by LIJI32** [comment]
The last commit should fix newer XNU versions where `thread_set_state` requires an entitlement. This requires setting a bootarg to disable AMFI, so make sure to run `make install` and reboot if required.
