### ISSUE TITLE
MIP - macOS Sequoia 15 issue

### ISSUE THREAD

**Issue by RegulusMac** [LIJI32/MIP#34]
Hello, today I tried out the new macOS Sequoia with MIP
and encountered the same problem as the latest Sonoma 14.5.

Do you know what install error 137 is?

Thx

[inject-2024-06-11-111355.ips.zip](https://github.com/user-attachments/files/15785798/inject-2024-06-11-111355.ips.zip)

**Comment by LIJI32** [comment]
Can you see if the latest version works on the beta?

**Comment by RegulusMac** [comment]
Hi, Yes it works on Sequoia. (Rosetta 2 not tested yet)

I can't test Sonoma 14.5 at the moment, cause I need to reinstall it first.
(Still using 14.4.1)

Will take some time, cause I'm busy these days.

Thank you very much!
