### ISSUE TITLE
On M1 Mac there's no way I can make install.. help?

### ISSUE THREAD

**Issue by silicooon** [LIJI32/MIP#9]
No matter what I've tried I get this error.
`mkdir -p build/injector/
cc -g -mmacosx-version-min=10.10 -I. -Werror -O3 -Wno-deprecated-declarations -isysroot  -arch arm64e -c injector/lsd_injector.c -o build/injector/lsd_injector.c.o
clang: error: no such file or directory: 'arm64e'
clang: error: no such sysroot directory: '-arch' [-Werror,-Wmissing-sysroot]
make: *** [build/injector/lsd_injector.c.o] Error 1`

**Comment by feedface** [comment]
you have no path-to-sdk after -isysroot flag. Check your xcodebuild settings.

**Comment by LIJI32** [comment]
As mentioned above, `xcodebuild` fails locating the SDK path. Running `xcodebuild -sdk macosx -version Path` manually should give you a more clear error.

**Comment by silicooon** [comment]
I found a way around guys! Thanks so much for MIP!
My issue was I've installed Command Line Tools before Xcode. Cheers!

**Comment by NSExceptional** [comment]
@silicooon You can close this issue if it is resolved!
